/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.13
 * Generated at: 2017-04-08 13:33:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminLocations_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/admintemplate/css.jsp", out, false);
      out.write("\n");
      out.write("\t<title>TixToGo Admin | Locations</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/admintemplate/header.jsp", out, false);
      out.write("\t\t\n");
      out.write("\t\t<div class=\"container bg-light-gray\">\n");
      out.write("\t\t\t<div class=\"main-content\">\n");
      out.write("                <div class=\"featured-heading\">\n");
      out.write("                    <h1 align=\"center\">Add Outdoor Cinema Location</h1>\n");
      out.write("                    <h2 align=\"center\">Please fill the entire form to provide the location details.</h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"ruler\"></div>\n");
      out.write("                \t<div class=\"featured-blocks\">\n");
      out.write("                \t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"span2\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"span7\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("  \t\t\t\t\t\t\t\t<label for=\"locationAddress\">Location Address</label>\n");
      out.write("  \t\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("    \t\t\t\t\t\t\t<textarea class=\"form-control\" id=\"locationAddress\" rows=\"2\"></textarea>\n");
      out.write("  \t\t\t\t\t\t\t\t</div>\n");
      out.write("  \t\t\t\t\t\t\t</div>\n");
      out.write("  \t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("  \t\t\t\t\t\t\t\t<label for=\"locationCapacity\">Capacity</label>\n");
      out.write("  \t\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("    \t\t\t\t\t\t\t<input class=\"form-control\" style=\"width: 200px\" type=\"number\" id=\"locationCapacity\">\n");
      out.write("  \t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("                        \t<br>\n");
      out.write("                        \t<br>\n");
      out.write("                        \t<div class=\"col-6\">\n");
      out.write("                        \t\t<button class=\"btn btn-simple btn-success btn-lg\" type=\"submit\">Add Location</button>\n");
      out.write("                        \t</div>\n");
      out.write("                        </div>\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"span3\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"ruler\"></div>\n");
      out.write("                <div class=\"featured-heading\">\n");
      out.write("                    <h1 align=\"center\">Edit Outdoor Cinema Location</h1>\n");
      out.write("                    <h2 align=\"center\">Make necessary changes here.</h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"ruler\"></div>\n");
      out.write("                <div class=\"featured-blocks\">\n");
      out.write("                \t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"span2\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("  \t\t\t\t\t\t\t\t<label for=\"movieID\">Location ID</label>\n");
      out.write("  \t\t\t\t\t\t\t\t<div class=\"col-12\">\n");
      out.write("    \t\t\t\t\t\t\t<input class=\"form-control\" style=\"width: 100px\" type=\"text\" id=\"movieID\">\n");
      out.write("  \t\t\t\t\t\t\t\t</div>\n");
      out.write("  \t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"span7\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("  \t\t\t\t\t\t\t\t<label for=\"locationAddress\">Location Address</label>\n");
      out.write("  \t\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("    \t\t\t\t\t\t\t<textarea class=\"form-control\" id=\"locationAddress\" rows=\"2\"></textarea>\n");
      out.write("  \t\t\t\t\t\t\t\t</div>\n");
      out.write("  \t\t\t\t\t\t\t</div>\n");
      out.write("  \t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("  \t\t\t\t\t\t\t\t<label for=\"locationCapacity\">Capacity</label>\n");
      out.write("  \t\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("    \t\t\t\t\t\t\t<input class=\"form-control\" style=\"width: 200px\" type=\"number\" id=\"locationCapacity\">\n");
      out.write("  \t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("                        \t<br>\n");
      out.write("                        \t<br>\n");
      out.write("                        \t<div class=\"col-6\">\n");
      out.write("                        \t\t<button class=\"btn btn-simple btn-success btn-lg\" type=\"submit\">Edit Location</button>\n");
      out.write("                        \t</div>\n");
      out.write("                        </div>\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"span3\"></div>\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("            \t\t</div>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t\t<div class=\"ruler\"></div>\n");
      out.write("                <div class=\"featured-heading\">\n");
      out.write("                    <h1 align=\"center\">View Locations</h1>\n");
      out.write("                    <h2 align=\"center\">List of locations.</h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"ruler\"></div>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("        \t</div>\n");
      out.write("        </div>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/admintemplate/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
