/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.13
 * Generated at: 2017-04-08 13:21:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminWelcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/admintemplate/css.jsp", out, false);
      out.write("\n");
      out.write("\t<title>TixToGo | Welcome Admin!</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/admintemplate/header.jsp", out, false);
      out.write("\n");
      out.write("\t\t<div class=\"wrap-bg\">\n");
      out.write("                <div class=\"site-header\">\n");
      out.write("                    <div class=\"logo\">\n");
      out.write("                        <h1>TixToGo</h1>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"container\">\n");
      out.write("                <div class=\"banner\">\n");
      out.write("                    <div class=\"carousel slide\" id=\"myCarousel\">\n");
      out.write("                           <!-- Carousel items -->\n");
      out.write("                                    <div class=\"carousel-inner\">\n");
      out.write("                                        <div class=\"item\">\n");
      out.write("                                            <img src=\"img/movieposters/au_flex_module_beautybeast_post_59bb4097.gif\" alt=\"\">\n");
      out.write("                                            <div class=\"carousel-caption\">\n");
      out.write("                                              <h1>Beauty and the Beast</h1>\n");
      out.write("                                              <h2>NOW SHOWING</h2>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"item active\">\n");
      out.write("                                            <img src=\"img/movieposters/NEtBI8JBb8UMxu_1_a.jpg\" alt=\"\">\n");
      out.write("                                            <div class=\"carousel-caption\">\n");
      out.write("                                              <h1>Logan</h1>\n");
      out.write("                                              <h2>NOW SHOWING</h2>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"item\">\n");
      out.write("                                            <img src=\"img/movieposters/Kong-Skull-Island-Poster.jpg\"\" alt=\"\">\n");
      out.write("                                            <div class=\"carousel-caption\">\n");
      out.write("                                              <h1>Kong - Skull Island</h1>\n");
      out.write("                                              <h2>Now Showing</h2>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>                                    \n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Carousel nav -->\n");
      out.write("                                    <a data-slide=\"prev\" href=\"#myCarousel\" class=\"carousel-control left\"></a>\n");
      out.write("                                    <a data-slide=\"next\" href=\"#myCarousel\" class=\"carousel-control right\"></a>\n");
      out.write("                        </div>\n");
      out.write("                \t</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"container bg-light-gray\">\n");
      out.write("              <div class=\"main-content\">\n");
      out.write("                <div class=\"featured-heading\">\n");
      out.write("                    <h1>Welcome Administrator!</h1>\n");
      out.write("                    <h2>To add, view or edit details, please check below.</h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"ruler\"></div>\n");
      out.write("                <div class=\"featured-blocks\">\n");
      out.write("                    <div class=\"row-fluid\">\n");
      out.write("                        <div class=\"span4\">\n");
      out.write("                            <div class=\"media\">\n");
      out.write("                              <div class=\"media-body\">\n");
      out.write("                                <h1 class=\"media-heading\">Manage movies</h1>\n");
      out.write("                                <p>IMPORTANT REMINDER: During expected release dates please \n");
      out.write("                                make sure to add the movie and its details and showing times.</p>\n");
      out.write("                               \n");
      out.write("                              <div class=\"checkmovies\">\n");
      out.write("                              <a href=\"adminMovies.jsp\" class=\"btn btn-danger\">Check movies now</a>\n");
      out.write("                              </div>\n");
      out.write("                             \n");
      out.write("                              </div>\n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"span4\">\n");
      out.write("                            <div class=\"media\">\n");
      out.write("                              <div class=\"media-body\">\n");
      out.write("                                <h1 class=\"media-heading\">Manage locations</h1>\n");
      out.write("                                <p>To add new locations, please add and update location details and the movies offered.</p>\n");
      out.write("                                <br>\n");
      out.write("                                <div class=\"checklocations\">\n");
      out.write("                              <a href=\"adminLocations.jsp\" class=\"btn btn-danger\">Check locations now</a>\n");
      out.write("                              </div>\n");
      out.write("                              </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"span4\">\n");
      out.write("                            <div class=\"media\">\n");
      out.write("                              <div class=\"media-body\">\n");
      out.write("                                <h1 class=\"media-heading\">Manage slots and reservations</h1>\n");
      out.write("                                <p>View customer's slot reservations and bookings for a movie here.</p>\n");
      out.write("                                <div class=\"checkslotreservations\">\n");
      out.write("                              <a href=\"adminReservations.jsp\" class=\"btn btn-danger\">Check slot reservations now</a>\n");
      out.write("                              </div>\n");
      out.write("                              </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/admintemplate/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
