/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-04-01 04:06:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.admintemplate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cssHomepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<head>\n");
      out.write("<title>TixToGo | Admin</title>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <!-- Facebook meta tags-->\n");
      out.write("    \t<meta property=\"og:title\" content=\"TixToGo | Admin\">\n");
      out.write("    \t<meta property=\"og:image\" content=\"\">\n");
      out.write("    \t<meta property=\"og:type\" content=\"website\">\n");
      out.write("    \t<meta property=\"og:site_name\" content=\"TixToGo | Admin\">\n");
      out.write("    <!-- Responsive meta tag-->\n");
      out.write("    \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    \t<meta http-equiv=\"X-UA-compatible\" content=\"IE=Edge\">\n");
      out.write("    \t<meta name=\"robots\" content=\"index, follow\">\n");
      out.write("    <!-- Description and keywords for search engines-->\n");
      out.write("    \t<meta name=\"description\" content=\"This is a portfolio template, coded in HTML 5 and CSS 3!\">\n");
      out.write("    \t<meta name=\"keywords\" content=\"Portfolio Template HTML5 CSS3 Javascript Custom\">\n");
      out.write("    \t<meta name=\"msapplication-TileColor\" content=\"#cdcec0\">\n");
      out.write("    \t<meta name=\"msapplication-TileImage\" content=\"/mstile-144x144.png\">\n");
      out.write("    \t<meta name=\"theme-color\" content=\"#ffffff\">\n");
      out.write("    <!-- Style sheets-->\n");
      out.write("    \t<link rel=\"stylesheet\" href=\"/css/all.css\">\n");
      out.write("    <!-- font link here, change to another google font if you wish!-->\n");
      out.write("    \t<link href=\"http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,700\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    \t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\">\n");
      out.write("    <!-- begin favicon stuff-->\n");
      out.write("    \t<link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"/img/apple-touch-icon-57x57.png\">\n");
      out.write("    \t<link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"/img/apple-touch-icon-60x60.png\">\n");
      out.write("    \t<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"/img/apple-touch-icon-72x72.png\">\n");
      out.write("    \t<link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"/img/apple-touch-icon-76x76.png\">\n");
      out.write("    \t<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"/img/apple-touch-icon-114x114.png\">\n");
      out.write("    \t<link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"/img/apple-touch-icon-120x120.png\">\n");
      out.write("    \t<link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"/img/apple-touch-icon-144x144.png\">\n");
      out.write("    \t<link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"/img/apple-touch-icon-152x152.png\">\n");
      out.write("    \t<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/img/apple-touch-icon-180x180.png\">\n");
      out.write("    \t<link rel=\"icon\" type=\"image/png\" href=\"/img/favicon-32x32.png\" sizes=\"32x32\">\n");
      out.write("    \t<link rel=\"icon\" type=\"image/png\" href=\"/img/android-chrome-192x192.png\" sizes=\"192x192\">\n");
      out.write("    \t<link rel=\"icon\" type=\"image/png\" href=\"/img/favicon-96x96.png\" sizes=\"96x96\">\n");
      out.write("    \t<link rel=\"icon\" type=\"image/png\" href=\"/img/favicon-16x16.png\" sizes=\"16x16\">\n");
      out.write("    \t<link rel=\"manifest\" href=\"/manifest.json\">\n");
      out.write("    <script src=\"js/jquery-2.1.4.min.js\"></script>\n");
      out.write("</head>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
